### ISSUE TITLE
Consider making `scanint` more effective

### ISSUE THREAD

**Issue by uxmal** [pedrommaiaa/Flow#1]
I realize this is a learning project, but it doesn't hurt to look at the code from a performance perspective to make it more efficient. You have a procedure `scanint` which is responsible for scanning integer literals. It loops, consuming characters until the end of the string is found:
```C
static int scanint(int c) 
{
  int k, val = 0;

  // Convert each character into an int value
  while ((k = chrpos("0123456789", c)) >= 0) 
  {
    val = val * 10 + k;
    c = next();
  }

  // We hit a non-integer character, put it back.
  putback(c);
  return (val);
}
```
Calling a procedure on each character is going to slow you down. The lexer is one of the most performance sensitive pieces of a compiler, because it has to touch every single character of the input file. You want to do as little work as possible for each character. Consider the following alternative implementation:
```C
static int scanint(int c)
{
    int k, val = 0;
    // Convert c from ASCII digit to integer.
    for (k = c - '0'; 0 <= k && k <= 9; c = next(), k = c - '0')
    {
        val = val * 10 + k;
        c = next();
    }

    // We hit a non-integer character, put it back.
    putback(c);
    return (val);
}
```
Here, we take each `c` and subtract `0` giving the digit value `k`. If `c` is a valid ASCII digit, `k` will be in the closed range [0..9].  We use the comma operator in the iterator expression of the for loop to both advance to the next character with `next()` and again convert the value to a digit value.

**Comment by xMasashi** [comment]
Thank you for taking your time to think about ways to improve this project,

It would definitely be better to subtract the ASCII value of '0' from c to make it an integer, but I used 
`(k = chrpos("0123456789", c)` so that in the future I would be able to convert hexadecimal digits as well, using something like `chrpos("0123456789abcdef")`.

What approach would you suggest in this case?

**Comment by uxmal** [comment]
If  you're dealing with ASCII characters, or UTF-8 characters, you could create a table lookup scheme. Define a 256-byte array, indexed by ASCII value, and containing the corresponding digit value. E.g if you have an 'A' hex digit in `c` , you use the ASCII value of 'A', which is 0x41 = 65 to index the array. At position 65, you place the digit value 10 corresponding to 'A'.

```C
#define XX ((unsigned char)0xFF)
const unsigned char hexdigitmap[256] =
{
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
     0,  1,  2,  3,  4,  5,  6,  7,   8,  9, XX, XX, XX, XX, XX, XX, 

    XX, 10, 11, 12, 13, 14, 15, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, 10, 11, 12, 13, 14, 15, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 

    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 

    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
    XX, XX, XX, XX, XX, XX, XX, XX,  XX, XX, XX, XX, XX, XX, XX, XX, 
};

int scanint(int c)
{
    int k, val = 0;
    // Convert c from ASCII digit to integer.
    for (k = hexdigitmap[(unsigned char)c]; k != XX; k = hexdigitmap[(unsigned char)c])
    {
        val = val * 10 + k;
        c = next();
    }

    // We hit a non-integer character, put it back.
    putback(c);
    return (val);
}
```
Now you're doing a load, a compare, and two arithmetic instructions per character (in addition to `next`). It doesn't get faster than that.

Next step is to make `next` an inline function or a macro, to make this blazingly fast. `putback` is not in a loop, so it's not quite as 'hot' as `next` is.

**Comment by xMasashi** [comment]
That's a very interesting approach, I will have to spend some time grasping this idea but I really appreciate that.
